name: Build Flutter APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. Configurer Java (Indispensable pour compiler l'APK avec Gradle)
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # 2. Configurer Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      # 3. Récupérer les dépendances
      - name: Install dependencies
        run: flutter pub get

      # 4. Générer les icônes de l'application (Évite l'erreur de ressource manquante)
      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons

      # 5. Compiler l'APK Release
      - name: Build APK
        run: flutter build apk --release

      # 6. Mettre à disposition l'APK en téléchargement
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Transport-Bransan-APK
          path: build/app/outputs/flutter-apk/app-release.apk